#!/bin/bash

URL="http://0.0.0.0:8000"
echo "----> Connecting with $URL"
echo "----> Creating/updating the path $3/$1"
mkdir -p /home/$3/$1/code && cat | tar -x -C /home/$3/$1/code
echo "----> Compressing files..."
cd /home/$3/$1/code && tar -zcvf ../code.tar.gz *
echo "----> Deploying app..."
echo "----> Processing information..."
echo "----> Setting up webserver rules..."
echo "----> Building docker container... (It might take a few minutes)"
curl \
  -G \
  -d "repo=$1&user=$3" \
  --silent $URL
